### PR TITLE
Ntd1hc/feat/issue 9/rename of key name

### PR DESCRIPTION
**Pull request by ngoan1608**
Hi Thomas,
Hi Holger,

This PR implements the renamed key in configuration json file for issue #9 .

Note: **The existing configuration json files in our project (related to aio-testtrigger) should be updated accordingly after merging this PR.**

Thank you,
Ngoan

### CODE REVIEW

**Review by HolQue — COMMENTED** [review]
Hi Ngoan,

like mentioned in

https://github.com/test-fullautomation/robotframework-robotlog2db/issues/29

the Test Trigger let both applications RobotLog2DB and PyTestLog2DB use the same configuration file.

Therefore it would be great if you adapt RobotLog2DB also to the renamed key - as soon as possible (only the implementation, adapting also the documentation you can deliver in addition later).

Without having both applications aligned here, the Test Trigger will not run.

**Comment by test-fullautomation** [comment]
Waiting for trigger to merge...

**Comment by ngoan1608** [comment]
Hi Thomas,

I added new commits which fixed other issues in this PR for testing all changes easily and avoid conflict in the built document.

1. Issue #10 is fixed with commit https://github.com/test-fullautomation/python-pytestlog2db/pull/20/commits/0cba8919712c2c55462381b5e9d0917aae0bf4fb
2. Issue #11 is fixed with commit https://github.com/test-fullautomation/python-pytestlog2db/pull/20/commits/15b8488c98744e4edd012cb0e4938a006120a658
3. Issue #14 is fixed with commit https://github.com/test-fullautomation/python-pytestlog2db/pull/20/commits/a6f9c8d6ca7624d8e41e89c2792cf5cffe83b171
4. Issue #18 is fixed with commit https://github.com/test-fullautomation/python-pytestlog2db/pull/20/commits/04f67b350cf55a2c1088f8402ea8c6024b740e68

Please review first and still wait for the changes in RobotLog2DB to merge this PR.

Thank you,
Ngoan

**Comment by ngoan1608** [comment]
Hi Holger,
Hi Thomas,

New commit https://github.com/test-fullautomation/python-pytestlog2db/pull/20/commits/664836982d5b2ed5561224bf6ef681a90b3294ab fixes the issue #7 by validating the xmlresultfile with junitxml schema at the very first step.


Thank you,
Ngoan

**Review by test-fullautomation — APPROVED** [review]
Hi Ngoan,
very good!
Thank you,
 Thomas

**Pull request merged**
